apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-quickstart
  namespace: default
spec:
  version: 7.10.2
  count: 1
  elasticsearchRef:
    name: quickstart
  kibanaRef:
    name: quickstart
  config:
    apm-server:
      rum.enabled: true
      ilm.enabled: true
  http:
    service:
      spec:
        type: LoadBalancer
    tls:
      selfSignedCertificate:
        disabled: true
